GET http://localhost:3000/api/v1/users/91b48493-c25e-4241-b4c4-c4d3796a6c4a
Accept: application/json

###
### Create Users
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Malika",
  "email": "malika@dummy.com",
  "password": "dummy123"
}

###
### Get All Products

GET http://localhost:3000/api/v1/users
Accept: application/json

### Create New Product
POST http://localhost:3000/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Mac Book Pro",
  "price": 40000000,
  "quantity": 10
}