GET http://localhost:3000/api/v1/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkIjoxNjUxNjIyMjI5LCJyb2xlIjoidXNlciIsInVzZXJfaWQiOiJhODZiZTAwOS0wNmQ5LTQ3MmUtOGJiNC0zMDM5NzA0MGE5N2MifQ.oDu2_7W0OMNI6jDOmVM4-P6I6HX_q7Io9tv8Nvty9nw

###
POST http://localhost:3000/api/v1/auths/login
Content-Type: application/json

{
  "email": "malika@dummy.com",
  "password": "dummy123"
}

###
GET http://localhost:3000/api/v1/users/91b48493-c25e-4241-b4c4-c4d3796a6c4a
Accept: application/json

###
### Create Users
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Malika",
  "email": "malika@dummy.com",
  "password": "dummy123"
}

###
### Get All Products

GET http://localhost:3000/api/v1/users
Accept: application/json

### Create New Product
POST http://localhost:3000/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Mac Book Pro",
  "price": 40000000,
  "quantity": 10
}